env_name: Lift
expert_policy: SAC_Lift
total_timesteps: 20000000
demo_size: 256
n_envs: 8
generator:
  type: SAC
  learning_starts: 10000
  batch_size: 256
  learning_rate: 3e-4
  gradient_steps: 1
evaluation:
  interval: 10000
  batch_size: 8
  save_interval: 100000
seed: 1
no_gpu: false
which_gpu: 0
suffix: BC_256
