env_name: Lift
expert_policy: PPO_Lift_OSC
use_human_demo: False
total_timesteps: 10000000
demo_size: 64
n_envs: 8
ac_vae:
  use_ac_vae: false
  n_iters: 100000
  latent_dim: 4
  batch_size: 256
  learning_rate: 3e-4
  kl_coef: 0.001
discriminator:
  use_disc: true
  reward_type: SOFTPLUS
  batch_size: 256
  learning_rate: 3e-5
  spectral_norm: False
generator:
  type: PPO
  learning_rate: 3e-4
  n_steps: 256
  batch_size: 256
evaluation:
  interval: 10000
  batch_size: 8
  save_interval: 100000
seed: 1
no_gpu: false
which_gpu: 0
suffix: GAIL_PPO_OSC
