env_name: Humanoid-v3
expert_policy: SAC_Humanoid-v3
total_timesteps: 6000000
demo_size: 64
n_envs: 8
ac_vae:
  use_ac_vae: false
  n_iters: 100000
  latent_dim: 4
  batch_size: 256
  learning_rate: 3e-4
  kl_coef: 0.0001
discriminator:
  use_disc: true
  reward_type: SOFTPLUS
  batch_size: 256
  learning_rate: 3e-5
generator:
  type: SAC
  learning_starts: 10000
  batch_size: 256
  learning_rate: 3e-4
  gradient_steps: 1
evaluation:
  interval: 10000
  batch_size: 8
  save_interval: 100000
seed: 1
no_gpu: false
which_gpu: 0
suffix: GAIL